### ISSUE TITLE
rstudio encountered a fatal error

### ISSUE THREAD

**Issue by Yufei-Cao** [MarWaltz/VCoVaR#1]
Rstudio encountered a fatal error when estimating V-CoVaR under multiple-normal copulas.

In function get_MCoVaR_VCoVaR, the following codes seem not working when multiple-normal copulas are used.

`copVul = rotCopula(copMulti)

MinF = function(v){
  vecV = rep(1-alpha, dim)
  vecV[Y_ind] = 1-v
  
  vecA = rep(1-alpha, dim)
  vecA[Y_ind] = 1
  
  return((v - pCopula(vecA, copula = copVul) + pCopula(vecV, copula = copVul)) - 
           (beta * (1 - pCopula(vecA, copula = copVul))))
}`

It seems that  'pCopula(vecA, copula = copVul)' is not working.

Any comments?

**Comment by MarWaltz** [comment]
Hi Yufei,

Thanks for your interest! There seems to be an issue with the copula-package. I created the following post with a minimal reproducible example:

https://r-forge.r-project.org/tracker/?func=detail&group_id=2140&aid=6818&atid=5417

I keep you updated if there is an reply.

Best,
Martin

**Comment by Yufei-Cao** [comment]
Dear Martin,

Thanks for your reply and information! The example confirms an issue of the copula package.

Regards,
Yufei
